### ISSUE TITLE
vim-json install

### ISSUE THREAD

**Issue by georgalis** [elzr/vim-json#46]
Hi, maybe sounds silly but could we have an install md? vim-json didn't work for me, maybe I'm not doing it right, or maybe I have wrong vim version or maybe.... who knows.

**Comment by elzr** [comment]
Hi georgalis. Sorry to hear vim-json is not working for you. As far as I can tell, installation problems are very rare which is why we don't yet have an install.md. I've tried to sprinkle troubleshooting advice throughout the readme.md. 

How is vim-json not working for you? Not at all or just in parts? You do have Pathogen & Vundle, right? Do you get an error message of some kind? What Vim version do you have? (vim version should only affect the concealing though, the rest of the plugin should work)

**Comment by georgalis** [comment]
Thanks elzr, I knew it was something simple... I didn't have the files in the correct location.

I'm just starting with json and having incorrect highlighting was problematic. A couple senetences in the top of the readme or separate install file about where to put vim-json, would go a long way. It has been a long time since I hacked highlighting and even though I knew, I forgot.

This happens to be my first (successful) experience with folding, but I think I got it figured out now. Looks like I have a very useful tool in place now!

As an observation, maybe the readme file is becoming over extended? might be looks like the 


README
quickstart
 install
 conceal
 folding (za) http://vim.wikia.com/wiki/Folding#Opening_and_closing_folds
