### ISSUE TITLE
autoindent issue

### ISSUE THREAD

**Issue by frimik** [elzr/vim-json#48]
vim 7.2, CentOS 6. Highlighting works fine (verifying with json-test.json), but indenting just removes all indentation ... Unsure what to try or provide as info ...

tried disabling all other plugins (from Vundle) but no change.

**Comment by elzr** [comment]
Hi @frimik, thanks for trying the plugin. OK, so what happens when you do `gg=G` (re-indent entire buffer) on json-test.json? The indenting of the page should improve a bit. You're saying what happens is that all lines become unindented and flush to the left side? 

I just checked it and the indenting is working fine for me. To be honest indenting is the part of the plugin I'm least familiar with, having inherited it from a previous maintainer.... I'll try to think of something and please let me know if you end up fixing it!

**Comment by frimik** [comment]
Yeah, `gg=G` indents entire buffer flush left (removes all leading whitespace).

It works on gvim 7.4 (on Windows)... as well as in the same console version which I run in msysgit bash: `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:33:40)`.

I share the same `vimrc` across my Windows machines and the Linux (CentOS 6) VM in question... (with a few **if** statements to make it work).

**Comment by nyerup** [comment]
I see this problem too, on the vim that comes with OSX:

:version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  6 2014 14:32:04)
[...]

**Comment by nyerup** [comment]
git bisect tells me, that commit 69ad31d3db4 broke autoindent.

**Comment by frimik** [comment]
Great, thanks @nyerup . I fixed my local copy like they did in this project:
fatih/vim-go#314

**Comment by elzr** [comment]
This is great stuff, I didn't know about git-bisect. :+1:  Thanks @nyerup for the fix & @frimik for bringing it up :)
